/**
 * Redux store actions
 */

 /* user */
 export const SET_USER_SIGN_IN_DATA = 'SET_USER_SIGN_IN_DATA'
 export const SIGN_OUT_USER = 'SIGN_OUT_USER'
 export const SET_SIGN_IN_ATTEMPTED = 'SET_SIGN_IN_ATTEMPTED'
 
 /* notebooks */
 export const ADD_USER_NOTEBOOK = 'ADD_USER_NOTEBOOK'
 export const SET_USER_NOTEBOOKS = 'SET_USER_NOTEBOOKS'
 export const UPDATE_USER_NOTEBOOK = 'UPDATE_USER_NOTEBOOK'
 export const REMOVE_USER_NOTEBOOK = 'REMOVE_USER_NOTEBOOK'
 export const CLEAR_USER_NOTEBOOKS = 'CLEAR_USER_NOTEBOOKS'

 /* notepages */
 export const ADD_USER_NOTEPAGE = 'ADD_USER_NOTEPAGE'
 export const SET_USER_NOTEPAGES = 'SET_USER_NOTEPAGES'
 export const UPDATE_USER_NOTEPAGE = 'UPDATE_USER_NOTEPAGE'
 export const REMOVE_USER_NOTEPAGE = 'REMOVE_USER_NOTEPAGE'
 export const SET_USER_SHARED = 'SET_USER_SHARED'
 export const CLEAR_USER_NOTEPAGES = 'CLEAR_USER_NOTEPAGES'

 /* editor */
 export const UPDATE_EDITOR_STYLES = 'UPDATE_EDITOR_STYLES'