/**
 * Redux store actions
 */

 /* user */
 export const SET_USER_SIGN_IN_DATA = 'SET_USER_SIGN_IN_DATA'
 
 /* notebooks */
 export const ADD_USER_NOTEBOOK = 'ADD_USER_NOTEBOOK'
 export const SET_USER_NOTEBOOKS = 'SET_USER_NOTEBOOKS'
 export const UPDATE_USER_NOTEBOOK = 'UPDATE_USER_NOTEBOOK'
 export const REMOVE_USER_NOTEBOOK = 'REMOVE_USER_NOTEBOOK'

 /* notepages */
 export const ADD_USER_NOTEPAGE = 'ADD_USER_NOTEPAGE'
 export const SET_USER_NOTEPAGES = 'SET_USER_NOTEPAGES'
 export const UPDATE_USER_NOTEPAGE = 'UPDATE_USER_NOTEPAGE'
 export const REMOVE_USER_NOTEPAGE = 'REMOVE_USER_NOTEPAGE'

 /* editor */
 export const UPDATE_EDITOR_STYLES = 'UPDATE_EDITOR_STYLES'